# Generated by Django 4.2.3 on 2025-06-25 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contraption',
            name='uuid',
        ),
        migrations.AddField(
            model_name='contraption',
            name='name_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
