# Generated by Django 4.2.3 on 2025-06-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_contraption_uuid_contraption_name_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaserScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ranges', models.JSONField()),
                ('contraption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laser_scans', to='index.contraption')),
            ],
        ),
    ]
