# Generated by Django 4.2.3 on 2025-06-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_laserscan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laserscan',
            name='ranges',
            field=models.CharField(max_length=1048576),
        ),
    ]
